### ISSUE TITLE
Implement macros / preprocessor

### ISSUE THREAD

**Issue by SciLor** [entropia/tip-toi-reveng#180]
To make it easier to write nice structured code it would be nice to have a preprocessor to make construction like that possible

```
scripts:
  bs_apfel:
    - $p_bs:=a $p_obj:=apfel $p_jmp:=_p_jmp_koestlich
    - J(_playBlock_jmp)

  bs_apfel2:
    - +playBlock_jmp(a, apfel, _p_jmp_koestlich)

  _p_jmp_koestlich:
    - P(koestlich, mhh_das_schmeckt, jam)

  _playBlock:
    - $p_jmp:=0
    - J(_play_jmp) P(nop)

  _playBlock_jmp:
    - P($p_bs) P(wait_0500ms)
    - P(wie_in) P(wait_0500ms)
    - P($p_obj) P(wait_1000ms)
    - $p_jmp!=0? J($p_jmp)

  _random:
    - T($r,65535) $random+=$r $random*=25173 $random+=13849 $ran2:=$random $ran2%=2 $ran3:=$random $ran3%=2 $ran4:=$random $ran4%=3
```

```
functions:
  playBlock_jmp:
    vars:
      - $p_bs
      - $p_obj
      - $p_jmp
    script:
      - J(_playBlock_jmp)
```

**Ideas**
- Allow code in multiple lines. The preprocessor should put everything in a single line. 
- If lines are to long, split them up automatically by using jumps
- Registeres are not possible with J/P. Analyse static code and generate all possiblities as code.
- Implement "functions" see  bs_apfel2
- Implement "imports" to split everything up into several files, just concat all subsections, if there are multiple "scripts" sections and throw an error if there are circling imports or multiple product-id sections
