### ISSUE TITLE
Modulo 5 - calculation wrong

### ISSUE THREAD

**Issue by SciLor** [entropia/tip-toi-reveng#185]
I am using following code to generate different random numbers:

```
  _random:
  - T($r,65535) $random+=$r $random*=25173 $random+=13849 J(_random_next) P(nop)
  _random_next:
  - $nextId2:=$random $nextId2%=2 $nextId3:=$random $nextId3%=3 $nextId4:=$random $nextId4%=4 J(_random_next2) P(nop)
  _random_next2:
  - $nextId5:=$random $nextId5%=5 $nextId6:=$random $nextId6%=6 $nextId7:=$random $nextId7%=7
```

I am using them to play random sounds:

Does not play anything if _random executed once or more times
```
  haus_buchstabe_b_error:
  - $nextId5==0? J(haus_bett) P(nop)
  - $nextId5==1? J(haus_bild_minnie) P(nop)
  - $nextId5==2? J(haus_bild_donald) P(nop)
  - $nextId5==3? J(haus_bild_pluto) P(nop)
  - $nextId5==4? J(haus_ev_badematte) P(nop)
```

Plays fine random sounds
```
  haus_buchstabe_b_works:
  - $nextId7==0? J(haus_bett) P(nop)
  - $nextId7==1? J(haus_bild_minnie) P(nop)
  - $nextId7==2? J(haus_bild_donald) P(nop)
  - $nextId7==3? J(haus_bild_pluto) P(nop)
  - $nextId7==4? J(haus_ev_badematte) P(nop)
  - $nextId7==5? J(haus_ev_badematte) P(nop)
  - $nextId7==6? J(haus_bett) P(nop)
```
