### ISSUE TITLE
code processing issue

### ISSUE THREAD

**Issue by DexCrane** [entropia/tip-toi-reveng#215]
Reference sayes, that commands must be spread over several lines of code if there are more than 8 commands. So the expected behaviour is, that all lines within a script related to an OID will be processed. My example
```yaml
product-id: 904
comment: testbed
init: $flag:=0
scripts:
  switch:
    - P(hear_this) J(bleep_again)
    - $flag == 0? $flag := 1 P(uno)
    - $flag == 1? $flag :=0 P(zero)
  bleep_again:
    - P(hear_this)
    - P(hear_this)
    - P(hear_this)
language: en
speak:
  zero: "switched from true to false"
  uno: "switched from false to true"
  hear_this: "bleep"
```
I used `tttool play <file.yaml>` to test the code. After entering `switch`, the "bleep" is played two times only. Following (conditional) lines related to `switch` are ignored as well as lines 2 and 3 related to `bleep_again`.
Is this a bug or by design?

**Comment by nomeata** [comment]
Yes, this is as expected: The pen will play the _first_ line of a script where all conditions match.

If you have more than 8 commands in one line, you need to spread them out over multiple _scripts_ and connect them with `J` commands:
```
scripts:
  switch:
    - P(hear_this) J(bleep_1)
    - $flag == 0? $flag := 1 P(uno)
    - $flag == 1? $flag :=0 P(zero)
  bleep_1:
    - P(hear_this) J(bleeb_2)
  bleep_2:
    - P(hear_this) J(bleeb_3)
  bleep_4:
    - P(hear_this) J(bleeb_5)
  bleep_5:
    - P(hear_this)
```
