### ISSUE TITLE
tttool play does not support T() command

### ISSUE THREAD

**Issue by DexCrane** [entropia/tip-toi-reveng#216]
For a game ("Das kleine Einmaleins") I try to generate the factors by random as follows:
```yaml
  calc_first_factor: T($r,65535) $rnd += $r $rnd *= 25173 $rnd += 13849 $factor1 %= 11 J(calc_next_factor)
  calc_next_factor: T($r,65535) $rnd += $r $rnd *= 25173 $rnd += 13849 $factor2 %= 11 J(calc_result)
  calc_result: $result := $factor1 $result *= $factor2 J(read_out_task)
```
Unfortunatelly the factors are always 0. `T($r,65535)` seems always to return `0`, doesn't it?
Or does this only work appropriately with the TipToi and not with `tttool play ...`?
