### ISSUE TITLE
`welcome` field trims quoted filenames

### ISSUE THREAD

**Issue by cstuder** [entropia/tip-toi-reveng#264]
Consider the following YAML:

```yaml
product-id: 900
welcome: "01 welcome.ogg"
scripts:
  ...
```

When assembling, this will search for the audio file `01.ogg` instead of `01 welcome.ogg`.

tttool 1.10 on MacOS 11.6.1.
