### ISSUE TITLE
GME Game programming

### ISSUE THREAD

**Issue by mgudemann** [entropia/tip-toi-reveng#295]
Hi, I have the "Mission im Lesedschungel" Tip Toi game.

Unfortunately card 16 is missing. So my idea is to change the OID in the game  for card 16 to some other card's OID and just use that., i.e., instead of clicking on card 16 one would click on card 17 and the game would continue.

I think there are sounds that read the content of the cards, so it should be possible to make this mission playable doing this, effectively unblocking the game.

Is there a good pointer to game programming / debugging? I only found `wip/games.txt` which did not really help me.

**Comment by nomeata** [comment]
It depends a bit on how that gme file is programmed. If it contains “binaries”, i.e. logic in machine code, then you cannot edit the gme file with tttool without losing functionality.

So the first thing you could try is to disassemble and assemble the file, load it onto the stick, and see if stuff still works.

**Comment by mgudemann** [comment]
@nomeata thanks, I will try that.
In the extracted yaml there are `unknown` entries for the games, could that be a problem?
for example:
```
  subgames:
  - oids1: 1 2 3 4 5 88
    unknown: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    oids3: ''
    oids2: ''
    playlist:
    - '344'
    - '345'
    - 346,343
    - 347,348,349
    - 350,351,352
    - []
    - []
    - []
    - []
```
